language: node_js
if: tag IS present
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
jobs:
  include:
  - script: npm run test:prod && npm run build
    node_js: lts/*
    after_success:
    - npm run report-coverage
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      npm run deploy-docs; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      npm run semantic-release; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: npm
  email: $NPM_USER
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: lmeysel/crud-client
  skip_cleanup: 'true'
