language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
script: npm run test:prod
jobs:
  include:
    - script: npm run test:prod && npm run build
      node_js:
        lts/*
      after_success:
        - npm run report-coverage
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy-docs; fi
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
