name: Node.js CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: |
        npm ci
        npm run test
        npm run build

    - name: Coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy docs
      run: npm run deploy-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
